// One suite for the 53 tiny tool test files
// this replaces. Each paid a full suite-loading cost to run at most
// 3 tests. Part files keep every case set in its own file without
// adding a suite, which is the split the file-size ratchet asks for.

import 'dart:convert';
import 'dart:io';
import 'package:caverno/core/services/browser_session_service.dart';
import 'package:caverno/features/chat/data/datasources/built_in_browser_tool_handler.dart';
import 'package:caverno/features/chat/data/datasources/built_in_computer_use_tool_handler.dart';
import 'package:caverno/features/chat/domain/services/tool_definition_search_service.dart';
import 'package:caverno/features/personal_eval/data/personal_eval_authored_corpus.dart';
import 'package:caverno/features/personal_eval/domain/entities/personal_eval_case.dart';
import 'package:crypto/crypto.dart';
import 'package:flutter_test/flutter_test.dart';
import '../../tool/chat_search_grounding_eval.dart';
import '../../tool/cli3_contention_soak.dart';
import '../../tool/cli3_contention_soak_report.dart';
import '../../tool/flutter_test_failure_set.dart';
import '../../tool/kc1_cutoff_oracle.dart';
import '../../tool/live_llm_benchmark_app_tool_profile.dart';
import '../../tool/live_llm_benchmark_warmup.dart';
import '../../tool/ll10_dependency_grounding_release_gate.dart';
import '../../tool/ll14_model_switch_handoff_measurement.dart';
import '../../tool/ll6_prefix_stability_measurement.dart';
import '../../tool/personal_eval_authored_operator.dart';
import '../../tool/personal_eval_experiment_protocol.dart';
import '../../tool/plan_mode_cli0_comparison_summary.dart';
import '../../tool/plan_mode_headless_canary_summary.dart';
import '../../tool/rag2_authority_claim_eval.dart';
import '../../tool/rag2_claim_support_eval.dart';
import '../../tool/rag2_compositional_holdout_eval.dart';
import '../../tool/rag2_evidence_sufficiency_eval.dart';
import '../../tool/rag2_explicit_source_roots_replay.dart';
import '../../tool/rag2_lexical_policy_bakeoff.dart';
import '../../tool/rag2_post_answer_claim_eval.dart';
import '../../tool/rag2_relation_aware_claim_eval.dart';
import '../../tool/rag2_semantic_claim_eval.dart';
import '../../tool/rag2_semantic_holdout_eval.dart';
import '../../tool/rag2_source_scope_measurement.dart';
import '../../tool/rag2_structured_claim_eval.dart';
import '../../tool/rag2_typed_fact_extraction_eval.dart';
import '../../tool/rag2_typed_fact_extraction_holdout_eval.dart';
import '../../tool/rag2_typed_fact_extraction_v2_eval.dart';
import '../../tool/rag2_typed_fact_extraction_v2_holdout_eval.dart';
import '../../tool/rag2_typed_fact_oracle_eval.dart';
import '../../tool/rag3_abstention_vector_instrument.dart';
import '../../tool/rag3_batched_support_filter_contract.dart';
import '../../tool/rag3_compact_support_filter_contract.dart';
import '../../tool/rag3_compact_support_filter_instrument.dart';
import '../../tool/rag3_instrument_eval.dart';
import '../../tool/rag3_promotion_run.dart';
import '../../tool/rag_retrieval_baseline.dart';
import '../../tool/rag_retrieval_eval.dart';
import '../../tool/rag_vector_baseline.dart';

part 'browser_save_live_canary_cases.dart';
part 'chat_search_grounding_eval_cases.dart';
part 'cli3_contention_soak_cases.dart';
part 'deploy_feedback_endpoint_cases.dart';
part 'desktop_single_instance_cases.dart';
part 'flutter_test_failure_set_cases.dart';
part 'ios_export_compliance_cases.dart';
part 'kc1_cutoff_oracle_cases.dart';
part 'live_llm_benchmark_app_tool_profile_cases.dart';
part 'live_llm_benchmark_warmup_cases.dart';
part 'll10_dependency_grounding_release_gate_cases.dart';
part 'll14_model_switch_handoff_measurement_cases.dart';
part 'll6_prefix_stability_measurement_cases.dart';
part 'macos_debug_bundle_id_cases.dart';
part 'personal_eval_mixed_task_repeatability_protocol_cases.dart';
part 'personal_eval_reconstruction_expansion_protocol_cases.dart';
part 'plan_mode_cli0_comparison_summary_cases.dart';
part 'plan_mode_headless_canary_summary_cases.dart';
part 'rag2_authority_claim_eval_cases.dart';
part 'rag2_claim_support_eval_cases.dart';
part 'rag2_compositional_holdout_eval_cases.dart';
part 'rag2_evidence_sufficiency_eval_cases.dart';
part 'rag2_explicit_source_roots_declaration_cases.dart';
part 'rag2_explicit_source_roots_holdout_declaration_cases.dart';
part 'rag2_post_answer_claim_eval_cases.dart';
part 'rag2_relation_aware_claim_eval_cases.dart';
part 'rag2_semantic_claim_eval_cases.dart';
part 'rag2_semantic_holdout_eval_cases.dart';
part 'rag2_source_scope_measurement_cases.dart';
part 'rag2_structured_claim_eval_cases.dart';
part 'rag2_typed_fact_extraction_eval_cases.dart';
part 'rag2_typed_fact_extraction_holdout_eval_cases.dart';
part 'rag2_typed_fact_extraction_v2_eval_cases.dart';
part 'rag2_typed_fact_extraction_v2_holdout_eval_cases.dart';
part 'rag2_typed_fact_oracle_eval_cases.dart';
part 'rag3_abstention_vector_instrument_cases.dart';
part 'rag3_compact_support_filter_instrument_cases.dart';
part 'rag3_instrument_eval_cases.dart';
part 'rag_vector_baseline_cases.dart';
part 'run_chat_search_grounding_eval_cases.dart';
part 'run_coding_expense_tracker_live_canary_cases.dart';
part 'run_coding_markdown_toc_live_canary_cases.dart';
part 'run_coding_stalled_diagnostic_repair_live_canary_cases.dart';
part 'run_coding_todo_app_mvp_live_canary_cases.dart';
part 'run_coding_word_frequency_live_canary_cases.dart';
part 'run_foundation_models_live_canary_cases.dart';
part 'run_ll37_routine_live_canary_cases.dart';
part 'run_ll37_worktree_agent_live_canary_cases.dart';
part 'run_personal_eval_suite_pipeline_cases.dart';
part 'run_plan_mode_todo_app_cli0_comparison_cases.dart';
part 'run_plan_mode_todo_app_headless_live_canary_cases.dart';
part 'run_plan_mode_todo_app_live_canary_cases.dart';
part 'run_pro_reasoning_live_canary_cases.dart';

void main() {
  _runBrowserSaveLiveCanary();
  _runChatSearchGroundingEval();
  _runCli3ContentionSoak();
  _runDeployFeedbackEndpoint();
  _runDesktopSingleInstance();
  _runFlutterTestFailureSet();
  _runIosExportCompliance();
  _runKc1CutoffOracle();
  _runLiveLlmBenchmarkAppToolProfile();
  _runLiveLlmBenchmarkWarmup();
  _runLl10DependencyGroundingReleaseGate();
  _runLl14ModelSwitchHandoffMeasurement();
  _runLl6PrefixStabilityMeasurement();
  _runMacosDebugBundleId();
  _runPersonalEvalMixedTaskRepeatabilityProtocol();
  _runPersonalEvalReconstructionExpansionProtocol();
  _runPlanModeCli0ComparisonSummary();
  _runPlanModeHeadlessCanarySummary();
  _runRag2AuthorityClaimEval();
  _runRag2ClaimSupportEval();
  _runRag2CompositionalHoldoutEval();
  _runRag2EvidenceSufficiencyEval();
  _runRag2ExplicitSourceRootsDeclaration();
  _runRag2ExplicitSourceRootsHoldoutDeclaration();
  _runRag2PostAnswerClaimEval();
  _runRag2RelationAwareClaimEval();
  _runRag2SemanticClaimEval();
  _runRag2SemanticHoldoutEval();
  _runRag2SourceScopeMeasurement();
  _runRag2StructuredClaimEval();
  _runRag2TypedFactExtractionEval();
  _runRag2TypedFactExtractionHoldoutEval();
  _runRag2TypedFactExtractionV2Eval();
  _runRag2TypedFactExtractionV2HoldoutEval();
  _runRag2TypedFactOracleEval();
  _runRag3AbstentionVectorInstrument();
  _runRag3CompactSupportFilterInstrument();
  _runRag3InstrumentEval();
  _runRagVectorBaseline();
  _runRunChatSearchGroundingEval();
  _runRunCodingExpenseTrackerLiveCanary();
  _runRunCodingMarkdownTocLiveCanary();
  _runRunCodingStalledDiagnosticRepairLiveCanary();
  _runRunCodingTodoAppMvpLiveCanary();
  _runRunCodingWordFrequencyLiveCanary();
  _runRunFoundationModelsLiveCanary();
  _runRunLl37RoutineLiveCanary();
  _runRunLl37WorktreeAgentLiveCanary();
  _runRunPersonalEvalSuitePipeline();
  _runRunPlanModeTodoAppCli0Comparison();
  _runRunPlanModeTodoAppHeadlessLiveCanary();
  _runRunPlanModeTodoAppLiveCanary();
  _runRunProReasoningLiveCanary();
}
