// One suite for the 20 tiny providers test files
// this replaces. Each paid a full suite-loading cost to run at most
// 3 tests. Part files keep every case set in its own file without
// adding a suite, which is the split the file-size ratchet asks for.

import 'dart:async';
import 'dart:collection';
import 'dart:io';
import 'package:caverno/core/services/app_lifecycle_service.dart';
import 'package:caverno/core/services/background_task_service.dart';
import 'package:caverno/core/services/notification_providers.dart';
import 'package:caverno/core/services/notification_service.dart';
import 'package:caverno/core/services/ssh_host_key.dart';
import 'package:caverno/core/services/ssh_known_hosts_store.dart';
import 'package:caverno/core/types/assistant_mode.dart';
import 'package:caverno/core/types/workspace_mode.dart';
import 'package:caverno/features/chat/data/datasources/app_database.dart';
import 'package:caverno/features/chat/data/datasources/chat_datasource.dart';
import 'package:caverno/features/chat/data/datasources/chat_remote_datasource.dart';
import 'package:caverno/features/chat/data/datasources/demo_datasource.dart';
import 'package:caverno/features/chat/data/datasources/llm_session_log_store.dart';
import 'package:caverno/features/chat/data/datasources/mcp_tool_service.dart';
import 'package:caverno/features/chat/data/datasources/parallel_slot_executor.dart';
import 'package:caverno/features/chat/data/datasources/save_skill_tool_runtime_adapter.dart';
import 'package:caverno/features/chat/data/repositories/chat_memory_repository.dart';
import 'package:caverno/features/chat/data/repositories/conversation_repository.dart';
import 'package:caverno/features/chat/data/repositories/conversation_repository_api.dart';
import 'package:caverno/features/chat/data/repositories/key_value_store.dart';
import 'package:caverno/features/chat/data/repositories/skill_repository.dart';
import 'package:caverno/features/chat/domain/entities/chat_turn_owner.dart';
import 'package:caverno/features/chat/domain/entities/coding_project.dart';
import 'package:caverno/features/chat/domain/entities/conversation.dart';
import 'package:caverno/features/chat/domain/entities/conversation_goal.dart';
import 'package:caverno/features/chat/domain/entities/conversation_participant.dart';
import 'package:caverno/features/chat/domain/entities/conversation_workflow.dart';
import 'package:caverno/features/chat/domain/entities/mcp_tool_entity.dart';
import 'package:caverno/features/chat/domain/entities/message.dart';
import 'package:caverno/features/chat/domain/entities/session_memory.dart';
import 'package:caverno/features/chat/domain/entities/skill.dart';
import 'package:caverno/features/chat/domain/entities/worktree_agent_task.dart';
import 'package:caverno/features/chat/domain/services/coding_diagnostic_feedback_service.dart';
import 'package:caverno/features/chat/domain/services/final_answer_claim_detector.dart';
import 'package:caverno/features/chat/domain/services/model_edit_apply_telemetry_recorder.dart';
import 'package:caverno/features/chat/domain/services/model_edit_apply_telemetry_service.dart';
import 'package:caverno/features/chat/domain/services/participant_turn_coordinator.dart';
import 'package:caverno/features/chat/domain/services/save_skill_tool_contract.dart';
import 'package:caverno/features/chat/domain/services/session_memory_service.dart';
import 'package:caverno/features/chat/domain/services/tool_execution_scheduler.dart';
import 'package:caverno/features/chat/presentation/providers/active_response_registry.dart';
import 'package:caverno/features/chat/presentation/providers/caverno_execution_runtime_provider.dart';
import 'package:caverno/features/chat/presentation/providers/chat_data_source_provider.dart';
import 'package:caverno/features/chat/presentation/providers/chat_notifier.dart';
import 'package:caverno/features/chat/presentation/providers/chat_ssh_tool_runtime.dart';
import 'package:caverno/features/chat/presentation/providers/chat_state.dart';
import 'package:caverno/features/chat/presentation/providers/coding_environment_snapshot_provider.dart';
import 'package:caverno/features/chat/presentation/providers/coding_projects_notifier.dart';
import 'package:caverno/features/chat/presentation/providers/coding_worktree_session_launcher.dart';
import 'package:caverno/features/chat/presentation/providers/conversations_notifier.dart';
import 'package:caverno/features/chat/presentation/providers/hidden_assistant_evidence_registry.dart';
import 'package:caverno/features/chat/presentation/providers/mcp_tool_provider.dart';
import 'package:caverno/features/chat/presentation/providers/model_edit_apply_telemetry_runtime_adapter.dart';
import 'package:caverno/features/chat/presentation/providers/parallel_slot_substrate_provider.dart';
import 'package:caverno/features/chat/presentation/providers/participant_turn_control_registry.dart';
import 'package:caverno/features/chat/presentation/providers/runtime_turn_event_publisher.dart';
import 'package:caverno/features/chat/presentation/providers/save_skill_notifier_runtime_store.dart';
import 'package:caverno/features/chat/presentation/providers/semantic_search_provider.dart';
import 'package:caverno/features/chat/presentation/providers/skills_notifier.dart';
import 'package:caverno/features/chat/presentation/providers/ssh_host_key_prompt_controller.dart';
import 'package:caverno/features/chat/presentation/providers/ssh_host_key_prompting_transport.dart';
import 'package:caverno/features/chat/presentation/providers/worktree_agent_git_reservation_probe.dart';
import 'package:caverno/features/chat/presentation/providers/worktree_agent_git_worktree_preparer.dart';
import 'package:caverno/features/chat/presentation/providers/worktree_agent_task_registry_notifier.dart';
import 'package:caverno/features/chat/presentation/providers/worktree_agent_task_starter.dart';
import 'package:caverno/features/chat/presentation/providers/worktree_agent_verification_runner.dart';
import 'package:caverno/features/settings/data/settings_repository.dart';
import 'package:caverno/features/settings/domain/entities/app_settings.dart';
import 'package:caverno/features/settings/domain/services/llm_sampler_preset_profile.dart';
import 'package:caverno/features/settings/domain/services/llm_sampler_runtime_feedback_service.dart';
import 'package:caverno/features/settings/presentation/providers/settings_notifier.dart';
import 'package:caverno_execution_runtime/caverno_execution_runtime.dart';
import 'package:drift/drift.dart' show driftRuntimeOptions;
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:mocktail/mocktail.dart';
import 'package:shared_preferences/shared_preferences.dart';

part 'caverno_execution_runtime_provider_cases.dart';
part 'chat_notifier_busy_thread_state_cases.dart';
part 'chat_notifier_plan_model_routing_cases.dart';
part 'chat_notifier_primary_model_routing_cases.dart';
part 'chat_notifier_python_attachment_repair_cases.dart';
part 'chat_notifier_turn_owner_snapshot_adoption_cases.dart';
part 'coding_diagnostic_feedback_provider_cases.dart';
part 'coding_worktree_session_launcher_cases.dart';
part 'hidden_assistant_evidence_registry_cases.dart';
part 'mcp_tool_provider_rollback_store_cases.dart';
part 'model_edit_apply_telemetry_runtime_adapter_cases.dart';
part 'parallel_slot_substrate_provider_cases.dart';
part 'participant_turn_control_registry_cases.dart';
part 'runtime_turn_event_publisher_cases.dart';
part 'save_skill_receipt_settlement_race_cases.dart';
part 'semantic_search_provider_cases.dart';
part 'ssh_host_key_prompting_transport_cases.dart';
part 'worktree_agent_git_reservation_probe_cases.dart';
part 'worktree_agent_task_starter_cases.dart';
part 'worktree_agent_verification_runner_cases.dart';

void main() {
  _runCavernoExecutionRuntimeProvider();
  _runChatNotifierBusyThreadState();
  _runChatNotifierPlanModelRouting();
  _runChatNotifierPrimaryModelRouting();
  _runChatNotifierPythonAttachmentRepair();
  _runChatNotifierTurnOwnerSnapshotAdoption();
  _runCodingDiagnosticFeedbackProvider();
  _runCodingWorktreeSessionLauncher();
  _runHiddenAssistantEvidenceRegistry();
  _runMcpToolProviderRollbackStore();
  _runModelEditApplyTelemetryRuntimeAdapter();
  _runParallelSlotSubstrateProvider();
  _runParticipantTurnControlRegistry();
  _runRuntimeTurnEventPublisher();
  _runSaveSkillReceiptSettlementRace();
  _runSemanticSearchProvider();
  _runSshHostKeyPromptingTransport();
  _runWorktreeAgentGitReservationProbe();
  _runWorktreeAgentTaskStarter();
  _runWorktreeAgentVerificationRunner();
}
