import Foundation

/// Checks that the watch decodes what the iPhone actually encodes.
///
/// The Dart tests prove what the phone writes and the watch target proves that
/// it compiles; neither proves the two agree. A renamed key or a new status
/// value crosses that boundary silently — the field simply arrives as its
/// default — and WATCH2 found ten defects at exactly this seam. The fixture is
/// generated by the Dart encoder, so this compares against the real wire
/// format rather than against a hand-written copy of it.
@main
enum WatchWireContractSmoke {
  static func main() throws {
    let arguments = CommandLine.arguments
    guard arguments.count == 2 else {
      FileHandle.standardError.write(
        Data("usage: watch_wire_contract_smoke <fixture.json>\n".utf8))
      exit(64)
    }
    let raw = try Data(contentsOf: URL(fileURLWithPath: arguments[1]))
    guard
      let document = try JSONSerialization.jsonObject(with: raw)
        as? [String: Any]
    else { fatalError("fixture is not a JSON object") }

    try checkSnapshot(document)
    try checkLegacySnapshot(document)
    checkCommands(document)
    checkStatuses(document)

    print("Watch wire contract passed")
  }

  private static func decode(
    _ document: [String: Any],
    _ key: String
  ) throws -> WatchSnapshot {
    guard let frame = document[key] else {
      fatalError("fixture has no \(key)")
    }
    let data = try JSONSerialization.data(withJSONObject: frame)
    return try JSONDecoder().decode(WatchSnapshot.self, from: data)
  }

  private static func checkSnapshot(_ document: [String: Any]) throws {
    let snapshot = try decode(document, "snapshot")

    expect(snapshot.sequence == 42, "sequence")
    expect(snapshot.sourceInstanceId == "source-a", "sourceInstanceId")
    expect(
      snapshot.sourceStartedAtMicros == 1_788_604_200_000_000,
      "sourceStartedAtMicros")
    expect(snapshot.conversationId == "conversation-1", "conversationId")
    expect(
      snapshot.conversationTitle == "Ship the companion", "conversationTitle")
    expect(snapshot.status == .awaitingGoalConfirmation, "status")
    expect(snapshot.needsAttention, "needsAttention")
    expect(
      snapshot.lastAssistantText == "The projection is in place.",
      "lastAssistantText")
    expect(snapshot.elapsedSeconds == 91, "elapsedSeconds")
    expect(snapshot.queuedCount == 2, "queuedCount")
    expect(snapshot.busyThreadCount == 3, "busyThreadCount")
    expect(snapshot.error == "Model unreachable", "error")

    expect(snapshot.workspaceMode == .coding, "workspaceMode")

    // The goal, which is the whole of WATCH9's wire surface.
    guard let goal = snapshot.goal else { fatalError("goal did not decode") }
    expect(goal.objective == "Put the goal on the wrist", "goal.objective")
    expect(goal.status == .awaitingConfirmation, "goal.status")
    expect(
      goal.completionSummary == "Bridge and views landed.",
      "goal.completionSummary")
    expect(
      goal.blockedReason == "dart analyze is failing", "goal.blockedReason")
    expect(
      snapshot.goalAwaitingConfirmation != nil, "goalAwaitingConfirmation")

    expect(snapshot.messages.count == 2, "messages.count")
    expect(snapshot.messages[0].role == .user, "messages[0].role")
    expect(snapshot.messages[0].text == "Is it done?", "messages[0].text")
    expect(snapshot.messages[1].isStreaming, "messages[1].isStreaming")
    expect(snapshot.messagesTruncated, "messagesTruncated")

    guard let approval = snapshot.approval else {
      fatalError("approval did not decode")
    }
    expect(approval.id == "approval-1", "approval.id")
    expect(approval.kind == "localCommand", "approval.kind")
    expect(approval.subtitle == "dart analyze", "approval.subtitle")
    expect(approval.canResolveOnWatch, "approval.canResolveOnWatch")

    guard let question = snapshot.question else {
      fatalError("question did not decode")
    }
    expect(question.id == "question-1", "question.id")
    expect(question.options.count == 2, "question.options.count")
    expect(question.allowMultiple, "question.allowMultiple")
    expect(question.allowOther, "question.allowOther")

    expect(snapshot.conversations.count == 3, "conversations.count")
    expect(snapshot.conversations[0].mode == nil, "conversations[0].mode")
    expect(snapshot.conversations[1].mode == .coding, "conversations[1].mode")
    expect(
      snapshot.conversations[2].mode == .routines, "conversations[2].mode")
    expect(snapshot.conversationsTruncated, "conversationsTruncated")
  }

  /// A frame from a phone that predates these fields must still render.
  ///
  /// The two apps ship as one bundle but are not guaranteed to be the same
  /// build at runtime, and a watch that refuses an older frame shows nothing
  /// at all.
  private static func checkLegacySnapshot(_ document: [String: Any]) throws {
    let snapshot = try decode(document, "legacySnapshot")

    expect(snapshot.conversationTitle == "Older phone", "legacy title")
    expect(snapshot.goal == nil, "legacy goal is absent")
    expect(snapshot.workspaceMode == nil, "legacy workspaceMode is absent")
    expect(snapshot.status == .idle, "legacy status")
    expect(!snapshot.needsAttention, "legacy needsAttention")
  }

  /// The reverse direction. A command the watch can send that the phone does
  /// not allow is a dead button, answered with `unsupported_command`.
  private static func checkCommands(_ document: [String: Any]) {
    guard let allowed = document["allowedCommands"] as? [String] else {
      fatalError("fixture has no allowedCommands")
    }
    let allowedSet = Set(allowed)
    let sent = Set(WatchCommandType.allCases.map(\.rawValue))

    expect(
      sent.subtracting(allowedSet).isEmpty,
      "the phone rejects: \(sent.subtracting(allowedSet).sorted())")
    expect(
      allowedSet.subtracting(sent).isEmpty,
      "the watch never sends: \(allowedSet.subtracting(sent).sorted())")
  }

  /// Every status the phone can send has to be one the watch names. An
  /// unnamed one decodes to `.idle`, which is how a goal awaiting
  /// confirmation looked before WATCH9.
  private static func checkStatuses(_ document: [String: Any]) {
    guard let names = document["statusNames"] as? [String] else {
      fatalError("fixture has no statusNames")
    }
    let known = Set(WatchTurnStatus.allCases.map(\.rawValue))
    let unknown = Set(names).subtracting(known)

    expect(unknown.isEmpty, "the watch decodes as idle: \(unknown.sorted())")
  }

  private static func expect(
    _ condition: Bool,
    _ what: String,
    file: StaticString = #file,
    line: UInt = #line
  ) {
    guard condition else {
      FileHandle.standardError.write(
        Data("wire contract failed: \(what) (line \(line))\n".utf8))
      exit(1)
    }
  }
}
