#!/usr/bin/env bash
# Proves that the watch decodes what the iPhone encodes.
#
# The Dart tests cover what the phone writes and `xcodebuild -target
# "CavernoWatch Watch App"` covers that the watch compiles. Neither covers the
# boundary between them, which is where WATCH2 found ten defects: a renamed key
# or an unnamed status crosses it silently, arriving as a default value.
#
# The fixture is generated by the Dart encoder rather than checked in, so this
# compares against the real wire format instead of a hand-written copy of it.
set -euo pipefail

cd "$(dirname "$0")/.."

out_dir="$(mktemp -d)"
trap 'rm -rf "$out_dir"' EXIT
fixture="$out_dir/watch_wire_fixture.json"
binary="$out_dir/watch_wire_contract_smoke"

dart_cmd=(dart)
if command -v fvm >/dev/null 2>&1 && [ -f .fvmrc ]; then
  dart_cmd=(fvm dart)
fi

"${dart_cmd[@]}" run tool/watch_wire_fixture.dart "$fixture" >/dev/null

swiftc \
  "ios/CavernoWatch Watch App/WatchModels.swift" \
  tool/watch_wire_contract_smoke.swift \
  -o "$binary"

"$binary" "$fixture"
