// Emits the wire contract the paired watch has to satisfy.
//
// The fixture is *generated by the Dart encoder* rather than written by hand:
// a hand-written fixture would only prove that Swift decodes whatever the
// fixture says, which is the same blind spot one layer up. The Swift side is
// checked against this output by tool/watch_wire_contract_smoke.sh.
import 'dart:convert';
import 'dart:io';

import 'package:caverno/features/watch/domain/watch_command.dart';
import 'package:caverno/features/watch/domain/watch_snapshot.dart';

void main(List<String> args) {
  if (args.length != 1) {
    stderr.writeln('usage: watch_wire_fixture.dart <output.json>');
    exitCode = 64;
    return;
  }

  // Every field the watch reads, with values a reader can recognise on the
  // other side. Text stays short so a truncation cap cannot silently change
  // what the Swift assertions compare against.
  final snapshot = WatchSnapshot(
    sequence: 42,
    generatedAt: DateTime.utc(2026, 9, 5, 12, 30),
    sourceInstanceId: 'source-a',
    sourceStartedAtMicros: 1788604200000000,
    conversationId: 'conversation-1',
    conversationTitle: 'Ship the companion',
    workspaceMode: 'coding',
    goal: const WatchGoal(
      objective: 'Put the goal on the wrist',
      status: 'awaitingConfirmation',
      completionSummary: 'Bridge and views landed.',
      blockedReason: 'dart analyze is failing',
    ),
    status: WatchTurnStatus.awaitingGoalConfirmation,
    lastAssistantText: 'The projection is in place.',
    messages: [
      WatchMessage(
        id: 'm-1',
        role: WatchMessageRole.user,
        text: 'Is it done?',
        timestamp: DateTime.utc(2026, 9, 5, 12, 28),
      ),
      WatchMessage(
        id: 'm-2',
        role: WatchMessageRole.assistant,
        text: 'Ask me from the wrist.',
        timestamp: DateTime.utc(2026, 9, 5, 12, 29),
        isStreaming: true,
      ),
    ],
    messagesTruncated: true,
    approval: const WatchApproval(
      id: 'approval-1',
      kind: 'localCommand',
      title: 'Run a command',
      subtitle: 'dart analyze',
      detail: 'Runs in the project root.',
      canResolveOnWatch: true,
    ),
    question: const WatchQuestion(
      id: 'question-1',
      question: 'Which endpoint?',
      options: [
        WatchQuestionOption(id: 'o-1', label: 'Local'),
        WatchQuestionOption(id: 'o-2', label: 'LAN'),
      ],
      allowMultiple: true,
      allowOther: true,
    ),
    elapsedSeconds: 91,
    queuedCount: 2,
    busyThreadCount: 3,
    conversations: const [
      WatchConversation(id: 'c-1', title: 'Chat thread'),
      WatchConversation(id: 'c-2', title: 'Coding thread', mode: 'coding'),
      WatchConversation(id: 'c-3', title: 'Routine thread', mode: 'routines'),
    ],
    conversationsTruncated: true,
    error: 'Model unreachable',
  );

  // A frame from a phone that predates these fields, so the watch's decoder is
  // held to the same forward-compatibility the Dart decoder is.
  final legacy = WatchSnapshot(
    sequence: 1,
    generatedAt: DateTime.utc(2026, 9, 5, 12),
    conversationTitle: 'Older phone',
    lastAssistantText: 'No goal here.',
  );

  // Written to a file rather than stdout: `dart run` prints build-hook
  // progress on stdout, which would corrupt the document.
  File(args.single).writeAsStringSync(
    jsonEncode({
      'snapshot': snapshot.toJson(),
      'legacySnapshot': legacy.toJson(),
      // The reverse direction: every command the watch can send has to be one
      // the phone will act on. A watch-only command is answered with
      // `unsupported_command`, which is diagnosable but still a dead button.
      'allowedCommands': WatchCommand.allowed.toList()..sort(),
      'statusNames': WatchTurnStatus.values
          .map((status) => status.name)
          .toList(),
    }),
  );
}
