// One suite for the chat domain-service cases that used to be 31 separate
// test files. Each file paid ~1.7 s of suite loading to run two or three
// tests, which is 53 s of the run's 1490 s of loading for 76 tests. Part files
// keep each case set in its own file without adding a suite, which is the
// split the file-size ratchet asks for.

import 'dart:convert';
import 'dart:io';
import 'package:caverno/core/security/conversation_taint_state.dart';
import 'package:caverno/core/types/workspace_mode.dart';
import 'package:caverno/features/chat/domain/entities/chat_turn_owner.dart';
import 'package:caverno/features/chat/domain/entities/conversation.dart';
import 'package:caverno/features/chat/domain/entities/conversation_goal.dart';
import 'package:caverno/features/chat/domain/entities/conversation_workflow.dart';
import 'package:caverno/features/chat/domain/entities/mcp_tool_entity.dart';
import 'package:caverno/features/chat/domain/entities/message.dart';
import 'package:caverno/features/chat/domain/entities/skill.dart';
import 'package:caverno/features/chat/domain/entities/tool_call_info.dart';
import 'package:caverno/features/chat/domain/services/anabasis_address.dart';
import 'package:caverno/features/chat/domain/services/background_process_follow_up_policy.dart';
import 'package:caverno/features/chat/domain/services/chat_request_prefix_stability_service.dart';
import 'package:caverno/features/chat/domain/services/coding_diagnostic_feedback_service.dart';
import 'package:caverno/features/chat/domain/services/conversation_checkpoint_recorder.dart';
import 'package:caverno/features/chat/domain/services/conversation_contract_provenance_service.dart';
import 'package:caverno/features/chat/domain/services/conversation_execution_recovery_service.dart';
import 'package:caverno/features/chat/domain/services/conversation_execution_summary_service.dart';
import 'package:caverno/features/chat/domain/services/conversation_goal_auto_continue_policy.dart';
import 'package:caverno/features/chat/domain/services/conversation_plan_diff_service.dart';
import 'package:caverno/features/chat/domain/services/conversation_plan_document_builder.dart';
import 'package:caverno/features/chat/domain/services/conversation_workflow_conflict_preservation_service.dart';
import 'package:caverno/features/chat/domain/services/conversation_workflow_stage_decision_receipt_service.dart';
import 'package:caverno/features/chat/domain/services/enabled_skill_named_in_text.dart';
import 'package:caverno/features/chat/domain/services/execution_budget_policy.dart';
import 'package:caverno/features/chat/domain/services/execution_snapshot_projector.dart';
import 'package:caverno/features/chat/domain/services/fenced_tool_name_blocks.dart';
import 'package:caverno/features/chat/domain/services/goal_auto_continue_prompt_builder.dart';
import 'package:caverno/features/chat/domain/services/goal_completion_elicitation_prompt.dart';
import 'package:caverno/features/chat/domain/services/immutable_json_snapshot.dart';
import 'package:caverno/features/chat/domain/services/kv_cache_warmup_service.dart';
import 'package:caverno/features/chat/domain/services/lsp_diagnostic_feedback_provider.dart';
import 'package:caverno/features/chat/domain/services/memory_extraction_json_parser.dart';
import 'package:caverno/features/chat/domain/services/memory_update_tool_use.dart';
import 'package:caverno/features/chat/domain/services/model_switch_handoff_brief_service.dart';
import 'package:caverno/features/chat/domain/services/participant_tool_policy.dart';
import 'package:caverno/features/chat/domain/services/pro_reasoning_models.dart';
import 'package:caverno/features/chat/domain/services/pro_reasoning_run_coordinator.dart';
import 'package:caverno/features/chat/domain/services/pro_reasoning_synthesis_recovery.dart';
import 'package:caverno/features/chat/domain/services/repo_map_lsp_symbol_cache.dart';
import 'package:caverno/features/chat/domain/services/session_memory_service.dart';
import 'package:caverno/features/chat/domain/services/stalled_diagnostic_repair_contract.dart';
import 'package:caverno/features/chat/domain/services/task_delegation_brief_builder.dart';
import 'package:caverno/features/chat/domain/services/task_proposal_parser.dart';
import 'package:caverno/features/chat/domain/services/tool_result_prompt_builder.dart';
import 'package:caverno/features/chat/domain/services/tool_result_taint_recorder.dart';
import 'package:caverno/features/chat/domain/services/truncation_notice.dart';
import 'package:caverno/features/chat/domain/services/turn_tool_catalog_cache.dart';
import 'package:caverno/features/chat/domain/services/turn_tool_catalog_source.dart';
import 'package:caverno/features/chat/domain/services/verification_cadence_policy.dart';
import 'package:caverno/features/chat/domain/services/workflow_proposal_parser.dart';
import 'package:caverno/features/chat/domain/services/workflow_task_proposal_quality_service.dart';
import 'package:caverno/features/settings/domain/entities/app_settings.dart';
import 'package:caverno_tool_contracts/caverno_tool_contracts.dart';
import 'package:flutter_test/flutter_test.dart';

part 'anabasis_address_cases.dart';
part 'background_process_follow_up_policy_cases.dart';
part 'chat_request_prefix_stability_service_cases.dart';
part 'command_diagnostic_streak_from_command_result_cases.dart';
part 'conversation_checkpoint_recorder_cases.dart';
part 'conversation_contract_provenance_service_cases.dart';
part 'conversation_execution_recovery_service_cases.dart';
part 'conversation_execution_summary_service_cases.dart';
part 'conversation_plan_diff_service_cases.dart';
part 'conversation_workflow_stage_decision_rehearsal_cases.dart';
part 'diagnostic_signature_cases.dart';
part 'execution_budget_policy_cases.dart';
part 'fenced_tool_name_blocks_cases.dart';
part 'goal_auto_continue_prompt_builder_cases.dart';
part 'goal_completion_elicitation_prompt_cases.dart';
part 'immutable_json_snapshot_cases.dart';
part 'kv_cache_warmup_service_cases.dart';
part 'lsp_diagnostic_feedback_provider_cases.dart';
part 'memory_extraction_json_parser_cases.dart';
part 'memory_update_and_skill_lookup_cases.dart';
part 'model_switch_handoff_brief_service_cases.dart';
part 'parsed_plan_delegation_cases.dart';
part 'participant_tool_policy_cases.dart';
part 'pro_reasoning_models_cases.dart';
part 'pro_reasoning_run_coordinator_cases.dart';
part 'pro_reasoning_synthesis_recovery_cases.dart';
part 'repo_map_lsp_symbol_cache_cases.dart';
part 'tool_result_taint_recorder_cases.dart';
part 'turn_tool_catalog_source_cases.dart';
part 'verification_cadence_policy_cases.dart';
part 'workflow_proposal_parser_cases.dart';

void main() {
  _runAnabasisAddress();
  _runBackgroundProcessFollowUpPolicy();
  _runChatRequestPrefixStabilityService();
  _runCommandDiagnosticStreakFromCommandResult();
  _runConversationCheckpointRecorder();
  _runConversationContractProvenanceService();
  _runConversationExecutionRecoveryService();
  _runConversationExecutionSummaryService();
  _runConversationPlanDiffService();
  _runConversationWorkflowStageDecisionRehearsal();
  _runDiagnosticSignature();
  _runExecutionBudgetPolicy();
  _runFencedToolNameBlocks();
  _runGoalAutoContinuePromptBuilder();
  _runGoalCompletionElicitationPrompt();
  _runImmutableJsonSnapshot();
  _runKvCacheWarmupService();
  _runLspDiagnosticFeedbackProvider();
  _runMemoryExtractionJsonParser();
  _runMemoryUpdateAndSkillLookup();
  _runModelSwitchHandoffBriefService();
  _runParsedPlanDelegation();
  _runParticipantToolPolicy();
  _runProReasoningModels();
  _runProReasoningRunCoordinator();
  _runProReasoningSynthesisRecovery();
  _runRepoMapLspSymbolCache();
  _runToolResultTaintRecorder();
  _runTurnToolCatalogSource();
  _runVerificationCadencePolicy();
  _runWorkflowProposalParser();
}
