import 'dart:convert';

import 'package:flutter_test/flutter_test.dart';

import 'package:caverno/features/chat/domain/entities/tool_call_info.dart';
import 'package:caverno/features/chat/domain/services/unwritten_file_claim_guard.dart';

void main() {
  const guard = UnwrittenFileClaimGuard();
  const root = '/workspace/project';

  ToolResultInfo successfulWrite(String path) {
    return ToolResultInfo(
      id: 'write-$path',
      name: 'write_file',
      arguments: {'path': path},
      result: jsonEncode({'path': '$root/$path', 'bytes_written': 12}),
    );
  }

  test('reports only an unbacked deliverable path that does not exist', () {
    final assessment = guard.assess(
      candidateResponse: '''
- `lib/a.dart` was created.
- `lib/b.dart` was created.
''',
      toolResults: [successfulWrite('lib/a.dart')],
      projectRoot: root,
      pathExists: (_) => false,
    );

    expect(assessment.claims, hasLength(1));
    expect(assessment.claims.single.displayPath, 'lib/b.dart');
    expect(assessment.claims.single.exists, isFalse);
    expect(assessment.buildNotice(), contains('does not exist'));
    expect(assessment.buildNotice(), isNot(contains('lib/a.dart')));
  });

  test('ignores an existing path without current-turn mutation evidence', () {
    final assessment = guard.assess(
      candidateResponse: '`lib/existing.dart` was updated.',
      toolResults: const [],
      projectRoot: root,
      pathExists: (_) => true,
    );

    expect(assessment.hasClaims, isFalse);
  });

  test('ignores an existing file generated by a successful command', () {
    final assessment = guard.assess(
      candidateResponse: '`lib/generated.g.dart` was updated.',
      toolResults: [
        ToolResultInfo(
          id: 'build-runner',
          name: 'local_execute_command',
          arguments: {'command': 'dart run build_runner build'},
          result: '{"exit_code":0}',
        ),
      ],
      projectRoot: root,
      pathExists: (path) => path == '$root/lib/generated.g.dart',
    );

    expect(assessment.hasClaims, isFalse);
  });

  test('ignores an existing file mentioned in a prior-turn summary', () {
    final assessment = guard.assess(
      candidateResponse: '`lib/prior.dart` was created in the previous turn.',
      toolResults: const [],
      projectRoot: root,
      pathExists: (path) => path == '$root/lib/prior.dart',
    );

    expect(assessment.hasClaims, isFalse);
  });

  test(
    'does not accept generic command success as proof for a missing file',
    () {
      final assessment = guard.assess(
        candidateResponse: '`todo.json` was created.',
        toolResults: [
          ToolResultInfo(
            id: 'generate-todo',
            name: 'local_execute_command',
            arguments: {'command': 'dart run bin/create_todo.dart'},
            result: '{"exit_code":0}',
          ),
        ],
        projectRoot: root,
        pathExists: (_) => false,
      );

      expect(assessment.claims.single.displayPath, 'todo.json');
      expect(assessment.claims.single.exists, isFalse);
      expect(assessment.buildNotice(), contains('does not exist'));
    },
  );

  test('recognizes completed Japanese mutation claims', () {
    final assessment = guard.assess(
      candidateResponse:
          '`lib/main.dart` \u3092\u65b0\u898f\u4f5c\u6210\u3057\u307e\u3057\u305f\u3002',
      toolResults: const [],
      projectRoot: root,
      pathExists: (_) => false,
    );

    expect(assessment.claims.single.displayPath, 'lib/main.dart');
  });

  test('recognizes direct mutation claims before and after the path', () {
    const responses = {
      'I created `lib/active.dart`.': 'lib/active.dart',
      'Created: `lib/labeled.dart`.': 'lib/labeled.dart',
      '`lib/passive.dart` was written.': 'lib/passive.dart',
      '`lib/parenthetical.dart` \uff08\u65b0\u898f\u4f5c\u6210\uff09':
          'lib/parenthetical.dart',
      '\u66f4\u65b0: `lib/japanese_label.dart`': 'lib/japanese_label.dart',
    };

    for (final entry in responses.entries) {
      final assessment = guard.assess(
        candidateResponse: entry.key,
        toolResults: const [],
        projectRoot: root,
        pathExists: (_) => false,
      );
      expect(
        assessment.claims.single.displayPath,
        entry.value,
        reason: entry.key,
      );
    }
  });

  test('recognizes direct multi-path deliverable list claims', () {
    const responses = [
      'Created: `lib/a.dart`, `lib/b.dart`.',
      '`lib/a.dart` and `lib/b.dart` were created.',
      '\u65b0\u898f\u4f5c\u6210: `lib/a.dart`\u3001`lib/b.dart`\u3002',
      '`lib/a.dart` \u3068 `lib/b.dart` \u3092\u66f4\u65b0\u3057\u307e\u3057\u305f\u3002',
    ];

    for (final response in responses) {
      final assessment = guard.assess(
        candidateResponse: response,
        toolResults: const [],
        projectRoot: root,
        pathExists: (_) => false,
      );
      expect(assessment.claims.map((claim) => claim.displayPath), [
        'lib/a.dart',
        'lib/b.dart',
      ], reason: response);
    }
  });

  test('recognizes paths in a completed-files Markdown table', () {
    final assessment = guard.assess(
      candidateResponse: '''
### \u4f5c\u6210\u3057\u305f\u30d5\u30a1\u30a4\u30eb

| \u30d5\u30a1\u30a4\u30eb | \u884c\u6570 | \u5f79\u5272 |
|---|---:|---|
| `lib/todo_cli.dart` | 248 | CLI |
| `lib/task_store.dart` | 128 | Store |
| `test/todo_cli_test.dart` | 163 | Tests |

### Verification
''',
      toolResults: const [],
      projectRoot: root,
      pathExists: (_) => false,
    );

    expect(assessment.claims.map((claim) => claim.displayPath), [
      'lib/todo_cli.dart',
      'lib/task_store.dart',
      'test/todo_cli_test.dart',
    ]);
  });

  test('ignores mutation words that describe something other than the file', () {
    const responses = [
      '`todo_app.md` says "prints the created task".',
      'todo_app.md says "prints the created task".',
      '`todo_app.md` describes how the task was created.',
      '`lib/a.dart` and `lib/b.dart` document the created task.',
      '`todo_app.md` \u306f\u300c\u4f5c\u6210\u3057\u305f\u30bf\u30b9\u30af\u3092\u8868\u793a\u3057\u307e\u3059\u300d\u3068\u8aac\u660e\u3057\u3066\u3044\u307e\u3059\u3002',
      '`lib/a.dart` \u3092\u66f4\u65b0\u3057\u3066\u3044\u307e\u305b\u3093\u3002',
    ];

    for (final response in responses) {
      final assessment = guard.assess(
        candidateResponse: response,
        toolResults: const [],
        projectRoot: root,
        pathExists: (_) => false,
      );
      expect(assessment.hasClaims, isFalse, reason: response);
    }
  });

  test('stays silent for plans, reads, mentions, and fenced examples', () {
    const responses = [
      '`lib/a.dart` will be created next.',
      'I plan to update `lib/a.dart`.',
      '`lib/a.dart` was inspected.',
      'The existing implementation is in `lib/a.dart`.',
      '```text\nlib/a.dart was created\n```',
      '`lib/a.dart` \u3092\u4f5c\u6210\u3057\u307e\u3059\u3002',
    ];

    for (final response in responses) {
      final assessment = guard.assess(
        candidateResponse: response,
        toolResults: const [],
        projectRoot: root,
        pathExists: (_) => false,
      );
      expect(assessment.hasClaims, isFalse, reason: response);
    }
  });

  test('stays silent for Japanese statements that updates are unnecessary', () {
    const responses = [
      '`lib/existing.dart` \u306e\u66f4\u65b0\u306f\u4e0d\u8981\u3067\u3059\u3002',
      '\u66f4\u65b0\u306f\u4e0d\u8981\u3067\u3059: `lib/existing.dart`',
      '`lib/existing.dart` \u306e\u66f4\u65b0\u306f\u5fc5\u8981\u304c\u306a\u3044\u3067\u3059\u3002',
    ];

    for (final response in responses) {
      final assessment = guard.assess(
        candidateResponse: response,
        toolResults: const [],
        projectRoot: root,
        pathExists: (_) => false,
      );
      expect(assessment.hasClaims, isFalse, reason: response);
    }
  });

  test('stays silent for backed mutations and paths outside the root', () {
    final assessment = guard.assess(
      candidateResponse: '''
- `lib/a.dart` was written.
- `/tmp/outside.dart` was created.
- `../../outside.dart` was updated.
''',
      toolResults: [successfulWrite('lib/a.dart')],
      projectRoot: root,
      pathExists: (_) => false,
    );

    expect(assessment.hasClaims, isFalse);
  });

  test('ignores failed file mutation results', () {
    final assessment = guard.assess(
      candidateResponse: '`lib/a.dart` was added.',
      toolResults: [
        ToolResultInfo(
          id: 'failed-write',
          name: 'write_file',
          arguments: const {'path': 'lib/a.dart'},
          result: jsonEncode({
            'path': '$root/lib/a.dart',
            'error': 'permission denied',
          }),
        ),
      ],
      projectRoot: root,
      pathExists: (_) => false,
    );

    expect(assessment.claims.single.displayPath, 'lib/a.dart');
  });
}
